### ISSUE TITLE
quest Icon sizes inconsistent

### ISSUE THREAD

**Issue by finalsliver** [FailcoderAddons/supervillain-ui#160]
![example](https://i.imgur.com/szn5q9E.png)

Similar to #129 though doesn't seem to be affected by portalling.
have seen normal sized icons on occaison buyt unsure how to replicate

**Comment by immortaltech** [comment]
I got you.
After doing the first quest (and using the item?) it was getting smaller.
First time
![1st](https://user-images.githubusercontent.com/7233566/30452921-9ba9778a-996d-11e7-81c9-78f4ebdf1a26.jpg)

Second Time
![2nd](https://user-images.githubusercontent.com/7233566/30452954-a4a4e73e-996d-11e7-86d2-5a073ce7ab61.jpg)

Then third time ( bye order resource)
![3rd](https://user-images.githubusercontent.com/7233566/30452977-b7ed2220-996d-11e7-93a9-f84bc4704914.jpg)

Couldnt test more because raid =/
