### ISSUE TITLE
UI is getting more and more un-usable

### ISSUE THREAD

**Issue by Elowan** [FailcoderAddons/supervillain-ui#195]
hi there,

I hope, there will be somebody to fix all the little bugs, that are getting more and more in number. With BfA around the corner, I really really hope, development is going strong again. It would be a real shame, to see this beautiful and feature-rich wow GUI gone forever.

Hope dies last!

ELo

**Comment by OrbitStorm** [comment]
There has been exactly one commit in the last six months and the majority of the prior commits have been done by someone who appears to just be a fan, making an effort to keep a functional baseline.

SVUI has historically been what amounts to abandonware. It's a shame because it doesn't appear that there is any interest in passing the project off to people willing to make a meaningful time investment.

I check back occasionally because this is my wife's favorite UI and she's desperately hoping it'll be revived but the reality is, I don't see this UI being an option by the time BFA drops.

**Comment by joeymagz** [comment]
Please submit useful bug information so that I can fix it. I do appreciate the feedback, but this is not the place for it. Please use our Discord for this, https://discord.gg/58AcatX
