### ISSUE TITLE
Can't view Artifact weapon relic nor click on any Relic weapons in bags

### ISSUE THREAD

**Issue by Balarium** [FailcoderAddons/supervillain-ui#88]
Firstly, im guessing i'm not the only one who has this problem.

The relic weapons are unclickable, both when equipped and when in bags. The icons are greyed out, and the ilvl dont show. I can change weapons from relic to something else, but not visa verca. Also i cannot add relics to weapons since when i try, Relic artifact window dont show when in class hall.
Its the only gamebreaking bug i have noticed after update.

I havent seen any other posts about this particular issue on the interwebs.

I was wondering if the dev(s) knew about his issue ?

If you all want i can see if i can get a bug report from SVUI next time i log on.

Thanks :)

**Comment by joeymagz** [comment]
This issue is fixed with the latest commits. libartifactdata library was out of date and has been updated to the latest version. It's recommended to do a fresh install and remove your cache folder, but you should also be able to just update that single file. I will keep this open for a few days before I close, to give you a chance to reply.
